# my first workflow
name: My-First-Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  first_job:
    name: Moje pierwsze zadanie
    runs-on: ubuntu-latest
    steps:
      - name: Pozdrowienia
        run: |
            echo "Hello ${{vars.WHO_TO_GREET}} from ${{github.actor}}."
            echo "My pass is #{{secrets.DMsecret01}}."
        shell: bash
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - run: tree
        
